// src/components/pressData.js
export const pressData = [
  {
    id: 1,
    title: "AI in Education: Transforming Learning",
    source: "Edutech News",
    date: "2025-09-01",
    summary: "Artificial Intelligence is revolutionizing classrooms by personalizing learning experiences.",
    image: "https://via.placeholder.com/400x250",
    link: "https://www.example.com/ai-in-education",
  },
  {
    id: 2,
    title: "Top 5 EdTech Tools for 2025",
    source: "Tech Daily",
    date: "2025-09-02",
    summary: "Discover the most innovative tools that are shaping the future of online learning.",
    image: "https://via.placeholder.com/400x250",
    link: "https://www.example.com/top-edtech-tools",
  },
  {
    id: 3,
    title: "Virtual Labs: The New Way of Learning Science",
    source: "EdTech Today",
    date: "2025-09-03",
    summary: "Virtual labs allow students to experiment and learn science safely and effectively.",
    image: "https://via.placeholder.com/400x250",
    link: "https://www.example.com/virtual-labs",
  },
  {
    id: 4,
    title: "Gamification in Learning: Boosting Engagement",
    source: "Learning Hub",
    date: "2025-09-04",
    summary: "Gamified learning strategies increase student engagement and motivation.",
    image: "https://via.placeholder.com/400x250",
    link: "https://www.example.com/gamification-learning",
  },
  {
    id: 5,
    title: "Online Learning Platforms Surge in 2025",
    source: "Tech EdNews",
    date: "2025-09-05",
    summary: "The demand for online education platforms is growing exponentially worldwide.",
    image: "https://via.placeholder.com/400x250",
    link: "https://www.example.com/online-platforms-2025",
  },
  {
    id: 6,
    title: "AR & VR: Immersive Learning Experiences",
    source: "EdTech Insights",
    date: "2025-09-06",
    summary: "Augmented and Virtual Reality tools are transforming practical learning sessions.",
    image: "https://via.placeholder.com/400x250",
    link: "https://www.example.com/ar-vr-education",
  },
  {
    id: 7,
    title: "Blockchain in Education: A Secure Future",
    source: "Future Learning",
    date: "2025-09-07",
    summary: "Blockchain technology ensures secure credentials and records in the education sector.",
    image: "https://via.placeholder.com/400x250",
    link: "https://www.example.com/blockchain-education",
  },
  {
    id: 8,
    title: "Personalized Learning Paths with AI",
    source: "Tech Learn",
    date: "2025-09-08",
    summary: "AI-driven platforms help students learn at their own pace and style.",
    image: "https://via.placeholder.com/400x250",
    link: "https://www.example.com/personalized-learning-ai",
  },
  {
    id: 9,
    title: "Coding Bootcamps: Fast-Track Your Career",
    source: "EdTech Today",
    date: "2025-09-09",
    summary: "Short-term intensive coding programs help students enter tech industries quickly.",
    image: "https://via.placeholder.com/400x250",
    link: "https://www.example.com/coding-bootcamps",
  },
  {
    id: 10,
    title: "Data Analytics in Education",
    source: "Learning Insights",
    date: "2025-09-10",
    summary: "Educational institutions are leveraging data analytics to improve student outcomes.",
    image: "https://via.placeholder.com/400x250",
    link: "https://www.example.com/data-analytics-education",
  },
  {
    id: 11,
    title: "EdTech Startups to Watch in 2025",
    source: "Tech Radar",
    date: "2025-09-11",
    summary: "A look at emerging startups innovating in the education technology space.",
    image: "https://via.placeholder.com/400x250",
    link: "https://www.example.com/edtech-startups-2025",
  },
  {
    id: 12,
    title: "Mobile Learning Apps: Learning On-the-Go",
    source: "EdTech Daily",
    date: "2025-09-12",
    summary: "Mobile apps allow students to access education anytime, anywhere.",
    image: "https://via.placeholder.com/400x250",
    link: "https://www.example.com/mobile-learning-apps",
  },
  {
    id: 13,
    title: "Gamified Assessment Tools for Teachers",
    source: "Tech Learn",
    date: "2025-09-13",
    summary: "Gamified assessments make testing more interactive and less stressful.",
    image: "https://via.placeholder.com/400x250",
    link: "https://www.example.com/gamified-assessment",
  },
  {
    id: 14,
    title: "Cloud-Based Classrooms Transform Education",
    source: "Future Learn",
    date: "2025-09-14",
    summary: "Cloud technologies enable flexible, scalable, and collaborative learning environments.",
    image: "https://via.placeholder.com/400x250",
    link: "https://www.example.com/cloud-classrooms",
  },
  {
    id: 15,
    title: "EdTech Conferences You Must Attend",
    source: "Learning Hub",
    date: "2025-09-15",
    summary: "Top conferences showcasing the latest trends in education technology.",
    image: "https://via.placeholder.com/400x250",
    link: "https://www.example.com/edtech-conferences",
  },
  {
    id: 16,
    title: "Digital Literacy Programs for Students",
    source: "Tech EdNews",
    date: "2025-09-16",
    summary: "Digital literacy initiatives are essential for preparing students for the modern world.",
    image: "https://via.placeholder.com/400x250",
    link: "https://www.example.com/digital-literacy",
  },
  {
    id: 17,
    title: "AI Tutors: Personalized Assistance",
    source: "EdTech Times",
    date: "2025-09-17",
    summary: "AI-powered tutors are helping students with personalized guidance and feedback.",
    image: "https://via.placeholder.com/400x250",
    link: "https://www.example.com/ai-tutors",
  },
  {
    id: 18,
    title: "Interactive E-Books: Redefining Learning",
    source: "Learning Today",
    date: "2025-09-18",
    summary: "Interactive e-books with multimedia content enhance comprehension and engagement.",
    image: "https://via.placeholder.com/400x250",
    link: "https://www.example.com/interactive-ebooks",
  },
  {
    id: 19,
    title: "Virtual Reality Field Trips for Students",
    source: "EdTech World",
    date: "2025-09-19",
    summary: "VR field trips give students immersive experiences without leaving the classroom.",
    image: "https://via.placeholder.com/400x250",
    link: "https://www.example.com/vr-field-trips",
  },
  {
    id: 20,
    title: "Future Skills: Preparing Students for 2030",
    source: "Tech Learn",
    date: "2025-09-20",
    summary: "Education is focusing on critical thinking, problem-solving, and digital skills for the future.",
    image: "https://via.placeholder.com/400x250",
    link: "https://www.example.com/future-skills",
  },
  {
    id: 21,
    title: "EdTech Tools for Special Needs Students",
    source: "Learning Insights",
    date: "2025-09-21",
    summary: "Innovative technology tools are making education more inclusive for students with special needs.",
    image: "https://via.placeholder.com/400x250",
    link: "https://www.example.com/special-needs-edtech",
  },
  {
    id: 22,
    title: "AI-Powered Language Learning Apps",
    source: "EdTech Daily",
    date: "2025-09-22",
    summary: "Language learning apps now use AI to customize lessons and improve retention.",
    image: "https://via.placeholder.com/400x250",
    link: "https://www.example.com/ai-language-apps",
  },
  {
    id: 23,
    title: "EdTech Innovations in STEM Education",
    source: "Tech EdNews",
    date: "2025-09-23",
    summary: "Cutting-edge tools are enhancing STEM education and hands-on learning.",
    image: "https://via.placeholder.com/400x250",
    link: "https://www.example.com/stem-edtech",
  },
  {
    id: 24,
    title: "Microlearning: Short & Effective Lessons",
    source: "Learning Hub",
    date: "2025-09-24",
    summary: "Microlearning breaks content into small, manageable lessons for better retention.",
    image: "https://via.placeholder.com/400x250",
    link: "https://www.example.com/microlearning",
  },
  {
    id: 25,
    title: "EdTech for Remote & Hybrid Classrooms",
    source: "Future Learning",
    date: "2025-09-25",
    summary: "Tools supporting remote and hybrid education are shaping the future of classrooms.",
    image: "https://via.placeholder.com/400x250",
    link: "https://www.example.com/remote-hybrid-edtech",
  }
];
